name: Update README Badge
description: Actualiza el badge de Cypress en el README
inputs:
  outcome:
    description: Resultado de Cypress (success|failure)
    required: true
runs:
  using: node20
  main: add_badge.js
